// <auto-generated />
using EcommerceSite.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceSite.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230204171303_Categories")]
    partial class Categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EcommerceSite.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("EcommerceSite.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Dune is a 1965 epic science fiction novel by American author Frank Herbert, originally published as two separate serials in Analog magazine. It tied with Roger Zelazny's This Immortal for the Hugo Award in 1966 and it won the inaugural Nebula Award for Best Novel. It is the first installment of the Dune saga. In 2003, it was described as the world's best-selling science fiction novel.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/de/Dune-Frank_Herbert_%281965%29_First_edition.jpg",
                            Price = 14.99m,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Evil Dead II (also known in publicity materials as Evil Dead 2: Dead by Dawn) is a 1987 American horror comedy film directed by Sam Raimi, who co-wrote it with Scott Spiegel, and produced by Robert Tapert. The film is the second installment in the Evil Dead film series and is considered both a remake and sequel to The Evil Dead (1981).The film stars Bruce Campbell as Ash Williams, who vacations with his girlfriend to a remote cabin in the woods. He discovers an audio tape of recitations from a book of ancient texts, and when the recording is played, it unleashes a number of demons which possess and torment him.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/6d/Evil_Dead_II_poster.jpg",
                            Price = 9.99m,
                            Title = "Evil Dead II"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "The themes include alienation and criticism of the music business. The bulk of the album is taken up by Shine On You Crazy Diamond, a nine-part tribute to founding member Syd Barrett, who left the band seven years earlier due to his deteriorating mental health. Barrett coincidentally visited during the album's production in 1975. Like their previous record, The Dark Side of the Moon (1973), Pink Floyd used studio effects and synthesisers. Guest singers included Roy Harper, who provided the lead vocals on Have a Cigar, and Venetta Fields, who added backing vocals to Shine On You Crazy Diamond. To promote the album, the band released the double A-side single Have a Cigar / Welcome to the Machine.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/Pink_Floyd%2C_Wish_You_Were_Here_%281975%29.png",
                            Price = 7.99m,
                            Title = "Wish You Were Here"
                        });
                });

            modelBuilder.Entity("EcommerceSite.Shared.Product", b =>
                {
                    b.HasOne("EcommerceSite.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
